version: '3.8'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data

  server:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - env/backend.env
      - env/postgres.env
    ports:
      - '80:80'
    depends_on:
      - db
  
  client:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - server
