version: '3.8'
services:
  db:
    image: 'postgres'
    restart: always
    env_file:
      - ./env/postgres.env
    ports:
      - '5432:5432'
    volumes:
      - dbVol:/var/lib/postgresql

  server:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    ports:
      - '80:80'
    depends_on:
      - db

  # react:
  #   build: ./
  #   ports:
  #     - "3000:3000"
  #   tty: true
  #   stdin_open: true
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules

volumes: 
  dbVol: